In [16]:
# !pip install --no-cache-dir pandas pyarrow
# !pip install openpyxl
!pip install tqdm

Collecting tqdm
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.68.3

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd
import requests
import json
import time
from tqdm import tqdm

In [3]:
gold_company = pd.read_excel("/Users/tiarasabrina/Documents/PROJECT/AI/address-parsing/master-data/master-matched/Master_Matching_20260701_1059 (1).xlsx", engine="openpyxl")
gold_company

,Company ID IDX,Company ID BUMN,Nama Perusahaan IDX,Nama Perusahaan BUMN,Nama Perusahaan AHU,Jaro IDX_BUMN,Jaro IDX_AHU,Jaro BUMN_AHU,Sektor,Sub Sektor,...,Kode Emiten (Ticker),Tanggal IPO (Listed),Papan Pencatatan,Alamat Lengkap,Telepon,Fax,Email,Website,NPWP,Pair Category
0,1.001,NaN,PT Adaro Andalan Indonesia Tbk,NaN,PT Adaro Andalan Indonesia,0.0,1.0,0.0,Energi,"Minyak, Gas & Batu Bara",...,AADI,2024-12-05,Utama,Cyber 2 Tower Lantai 26\nJl. H.R. Rasuna Said ...,(021) 2553 3065 | 02125533000,(021) 2553 3066,corsec@adaroindonesia.com,www.adaroindonesia.com,02.433.115.9-091.000,IDX + AHU
1,1.002,NaN,Adaro Australia Pty Ltd,NaN,NaN,0.0,0.0,0.0,Investasi,Investasi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IDX Only
2,1.003,NaN,Adaro Capital Limited,NaN,NaN,0.0,0.0,0.0,Investasi,Investasi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IDX Only
3,1.004,NaN,Adaro International (Singapore) Pte Ltd,NaN,NaN,0.0,0.0,0.0,Perdagangan batubara,Perdagangan batubara,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IDX Only
4,1.005,NaN,Arindo Holdings (Mauritius) Ltd,NaN,NaN,0.0,0.0,0.0,Investasi,Investasi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IDX Only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772560,NaN,NaN,NaN,NaN,PT Fatima Trading Companies,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,"Gedung Fancy Mampang, Jl. Mampang Prpt. Raya N...",0881024990317,NaN,NaN,NaN,NaN,AHU Only
772561,NaN,NaN,NaN,NaN,PT Simpul Eventworks Indonesia,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,Jl. Wolter Monginsidi No.107A,087784451067,NaN,NaN,NaN,NaN,AHU Only
772562,NaN,NaN,NaN,NaN,PT Sinar Fajar Nusantara Kilat,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,Jalan Ancol Barat VIII Nomor 1 Kontener Nomor ...,081387119253,NaN,NaN,NaN,NaN,AHU Only
772563,NaN,NaN,NaN,NaN,PT Stasiun Hangat Sejahtera,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,"Infiniti Office, Bellezza BSA, 1st Floor Unit ...",082364055502,NaN,NaN,NaN,NaN,AHU Only
772564,NaN,NaN,NaN,NaN,PT Kilat Debris Mandiri,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,"GEDUNG THAMRIN CITY, LANTAI 6, UNIT 607, JL. T...",081928719381,NaN,NaN,NaN,NaN,AHU Only

In [4]:
gold_company_address = gold_company[["Alamat Lengkap"]]
gold_company_address

                                           Alamat Lengkap
0       Cyber 2 Tower Lantai 26\nJl. H.R. Rasuna Said ...
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
772560  Gedung Fancy Mampang, Jl. Mampang Prpt. Raya N...
772561                      Jl. Wolter Monginsidi No.107A
772562  Jalan Ancol Barat VIII Nomor 1 Kontener Nomor ...
772563  Infiniti Office, Bellezza BSA, 1st Floor Unit ...
772564  GEDUNG THAMRIN CITY, LANTAI 6, UNIT 607, JL. T...

[772565 rows x 1 columns]

In [5]:
#count NaN address
gold_company_address.isnull().sum()

Alamat Lengkap    6862
dtype: int64

In [6]:
df_sample = gold_company_address[
    gold_company_address["Alamat Lengkap"].str.len() > 30
].sample(n=1000, random_state=42)

In [10]:
df_sample

                                           Alamat Lengkap
771473  JALAN RAYA CILINCING NO 36, RUKO CILINCING PLA...
705059  JALAN CENDRAWASIH PERUMAHAN TAHAP 3 NOMOR 4, K...
751424  SEDAYU SQUARE Blok B 12, JALAN OUTER RINGROAD ...
684392              GRAHA MULIA, CLUSTER DIAMOND, BLOK P7
286020  Ruko Thematik Paramount Marketplace Blok P/51 ...
...                                                   ...
108374       4W OFFICE, JALAN RING ROAD BUBULAK NOMOR A-4
767431             Northwest Boulevard NV 07/6 (Lantai 2)
317657  SPAZIO TOWER LANTAI 11 UNIT 1107 Jl. Mayjend Y...
343277           WIJAYA GRAND CENTER, JL. WIJAYA II NO.15
327611  Gedung Grand Slipi Tower Lantai 5 unit F. Jala...

[1000 rows x 1 columns]

In [ ]:
def parse_address(alamat):
    prompt = f"""
Ekstrak alamat berikut ke JSON.

Aturan:
- Jangan mengarang.
- Jika tidak ada, isi "".
- Semua teks yang tidak masuk field lain masukkan ke remaining_text.
- Output JSON valid saja.

Alamat:
{alamat}

{{
  "gedung": "",
  "lantai": "",
  "jalan": "",
  "no": "nomor ..",
  "kelurahan": "",
  "kecamatan": "",
  "kota": "",
  "provinsi": "",
  "kodepos": "",
  "remaining_text": ""
}}
"""
    
    try:
        r = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": "qwen2.5:7b",
                "prompt": prompt,
                "format": "json",
                "stream": False,
                "options": {
                    "temperature": 0,
                    "num_predict": 120,
                    "num_ctx": 512
                }
            },
            timeout=60
        )

        raw = r.json()
        return json.loads(raw["response"])

    except Exception as e:
        print("ERROR:", e)
        return None

In [21]:
import json

sample = df_sample["Alamat Lengkap"].iloc[0]

result = parse_address(sample)

print("=== ORIGINAL ===")
print(sample)

print("\n=== PARSED ===")
print(json.dumps(result, indent=2, ensure_ascii=False))

=== ORIGINAL ===
JALAN RAYA CILINCING NO 36, RUKO CILINCING PLAZZA BLOK A/2

=== PARSED ===
{
  "gedung": "",
  "lantai": "",
  "jalan": "JALAN RAYA CILINCING",
  "no": "36",
  "kelurahan": "",
  "kecamatan": "",
  "kota": "",
  "provinsi": "",
  "kodepos": "",
  "remaining_text": "RUKO CILINCING PLAZZA BLOK A/2"
}

In [22]:
from tqdm import tqdm
import pandas as pd
import time
import json

dataset = []
failed = []

for i, addr in enumerate(tqdm(df_sample["Alamat Lengkap"].head(1000), total=1000)):

    result = parse_address(addr)

    if result is not None:
        dataset.append({
            "text": addr,
            "label": result
        })
    else:
        failed.append({
            "text": addr,
            "idx": i
        })

    # checkpoint tiap 25 data (WAJIB biar nggak nyesel 😭)
    if (i + 1) % 25 == 0:
        pd.DataFrame(dataset).to_json(
            "dataset_checkpoint.json",
            orient="records",
            force_ascii=False,
            indent=2
        )

        pd.DataFrame(failed).to_json(
            "failed_checkpoint.json",
            orient="records",
            force_ascii=False,
            indent=2
        )

    time.sleep(0.02)  # ringan aja, biar Ollama nggak overheat

 32%|███▏      | 322/1000 [37:57<1:21:33,  7.22s/it]

ERROR: Unterminated string starting at: line 11 column 21 (char 290)

 58%|█████▊    | 583/1000 [1:09:39<56:01,  8.06s/it]

ERROR: Expecting ',' delimiter: line 12 column 1 (char 293)

 89%|████████▉ | 893/1000 [1:50:02<12:53,  7.23s/it]

ERROR: Unterminated string starting at: line 11 column 21 (char 218)

100%|██████████| 1000/1000 [2:02:15<00:00,  7.34s/it]

In [23]:
dataset

[{'text': 'JALAN RAYA CILINCING NO 36, RUKO CILINCING PLAZZA BLOK A/2',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JALAN RAYA CILINCING',
   'no': '36',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'RUKO CILINCING PLAZZA BLOK A/2'}},
 {'text': 'JALAN CENDRAWASIH PERUMAHAN TAHAP 3 NOMOR 4, KOTA DURI, KABUPATEN BENGKALIS',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JALAN CENDRAWASIH',
   'no': '4',
   'kelurahan': '',
   'kecamatan': '',
   'kota': 'KOTA DURI',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'PERUMAHAN TAHAP 3'}},
 {'text': 'SEDAYU SQUARE Blok B 12, JALAN OUTER RINGROAD LKR. LUAR',
  'label': {'gedung': 'SEDAYU SQUARE',
   'lantai': '',
   'jalan': 'JALAN OUTER RINGROAD LKR. LUAR',
   'no': 'Blok B 12',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'GRAHA MULIA, CLUSTER DIAMOND, BLOK P7',
  'label': {'gedung': 'GRAHA MULIA',
   'lantai': '',
   'jalan': '',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'CLUSTER DIAMOND, BLOK P7'}},
 {'text': 'Ruko Thematik Paramount Marketplace Blok P/51 Jalan CBD Gading Serpong Selatan',
  'label': {'gedung': 'Ruko Thematik Paramount Marketplace',
   'lantai': '',
   'jalan': 'CBD Gading Serpong Selatan',
   'no': 'Blok P/51',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'GREEN HUB LEVEL 38 TOWER A, KOTA KASABLANKA, JL. CASABLANCA RAYA KAV.88',
  'label': {'gedung': 'GREEN HUB',
   'lantai': '38',
   'jalan': 'JL. CASABLANCA RAYA',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': 'KOTA KASABLANKA',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'TOWER A, JL. CASABLANCA RAYA KAV.88'}},
 {'text': 'Jl. Paus, Gang Masjid Urwatul Wutsqo, No.07',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jl. Paus',
   'no': '07',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Gang Masjid Urwatul Wutsqo'}},
 {'text': 'Jalan Senopati Nomor 8B, Office 8 Lantai 12',
  'label': {'gedung': '',
   'lantai': '12',
   'jalan': 'Jalan Senopati',
   'no': '8B',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Office 8'}},
 {'text': 'Jalan Batununggal Kav. C Nomor 6',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Batununggal',
   'no': 'C6',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Kavling Rancamas Blok J, Nomor 49',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Rancamas',
   'no': '49',
   'blok': 'J',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Ruko Mutiara Taman Palem Blok C5 Lt. 1 No. 3 Jl. Kamal Raya',
  'label': {'gedung': 'Ruko Mutiara',
   'lantai': 'Lt. 1',
   'jalan': 'Jl. Kamal Raya',
   'no': '3',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Blok C5'}},
 {'text': 'Gedung Wirausaha Lantai 1 Unit 104, Jalan HR Rasuna Said Kav. C-5',
  'label': {'gedung': 'Gedung Wirausaha',
   'lantai': '1',
   'jalan': 'Jalan HR Rasuna Said',
   'no': 'Kav. C-5',
   'unit': 'Unit 104',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Jl. By Pass Ngurah Rai, Perum. Taman Jimbaran III No. 15, Lingk. Perarudan Jimbaran',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jl. By Pass Ngurah Rai',
   'no': '15',
   'kelurahan': 'Perarudan Jimbaran',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Perum. Taman Jimbaran III'}},
 {'text': 'CENTENNIAL TOWER Lantai 35 Unit A & B, JL. JEND. GATOT SUBROTO Kaveling 24-25',
  'label': {'gedung': 'CENTENNIAL TOWER',
   'lantai': '35',
   'jalan': 'JL. JEND. GATOT SUBROTO',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Unit A & B, Kaveling 24-25'}},
 {'text': 'Jalan Mahligai Komplek Damai Nomor 9',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Mahligai',
   'no': '9',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Komplek Damai'}},
 {'text': 'JL. EROPA I KAV I STAGE II/4 KIEC',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL. EROPA I',
   'no': 'KAV I STAGE II/4',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'KIEC'}},
 {'text': 'Jalan Yudistira I, Wonokarto Barat',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Yudistira I',
   'no': '',
   'kelurahan': '',
   'kecamatan': 'Wonokarto Barat',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Jalan Raya Karansinom Ruko Pawarengan Residence No 03',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Raya Karansinom',
   'no': '03',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Ruko Pawarengan Residence'}},
 {'text': 'JALAN DR. SUTOMO NOMOR 4 GEDUNG GRIYA SINTESA LANTAI 3',
  'label': {'gedung': 'GRIYA SINTESA',
   'lantai': '3',
   'jalan': 'JALAN DR. SUTOMO',
   'no': '4',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Worktren, Jl. Jalur Sutera Barat Alam Sutera No. 38K',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jl. Jalur Sutera Barat',
   'no': '38K',
   'kelurahan': 'Alam Sutera',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Worktren'}},
 {'text': 'Cityloft unit 2217 , Jl KH Mas Mansyur',
  'label': {'gedung': 'Cityloft',
   'lantai': '2217',
   'jalan': 'Jl KH Mas Mansyur',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'GEDUNG GRANADA REGATAMA LANTAI 3 UNIT B 503 DAN 505, JALAN PARIAMAN NOMOR 1',
  'label': {'gedung': 'GRANADA REGATAMA',
   'lantai': '3',
   'jalan': 'PARIAMAN',
   'no': '1',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'UNIT B 503 DAN 505'}},
 {'text': 'Graha Familymart, Jalan Setiabudi Selatan Kaveling 10',
  'label': {'gedung': 'Graha Familymart',
   'lantai': '',
   'jalan': 'Jalan Setiabudi Selatan',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Kaveling 10'}},
 {'text': 'MTH Square Ground Floor (GF) A4 A, Jl. Letjen M.T. Haryono Kav. 10',
  'label': {'gedung': 'MTH Square',
   'lantai': 'Ground Floor (GF)',
   'jalan': 'Jl. Letjen M.T. Haryono',
   'no': 'Kav. 10',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Alamanda Tower Lantai 2 Unit H1 JL. TB. Simatupang Kav 23-24',
  'label': {'gedung': 'Alamanda Tower',
   'lantai': '2',
   'jalan': 'JL. TB. Simatupang',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Unit H1 Kav 23-24'}},
 {'text': 'Rukan The Avenue 8-038, Perumahan Jakarta Garden City',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'The Avenue',
   'no': '8-038',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Perumahan Jakarta Garden City'}},
 {'text': 'JL. KARTAMA NO. 74 GEDUNG GRAHA YK Lt.3',
  'label': {'gedung': 'GRAHA YK',
   'lantai': '3',
   'jalan': 'JL. KARTAMA',
   'no': '74',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Pergudangan Surya Balaraja Blok H Kav. No.18',
  'label': {'gedung': 'Pergudangan Surya Balaraja',
   'lantai': '',
   'jalan': '',
   'no': '18',
   'kelurahan': '',
   'kecamatan': 'Balaraja',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Jalan Arteri Gading Blok E1 No. 09',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Arteri Gading',
   'no': 'E1 No. 09',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'JL.GAJAH MADA NO 174B,DS KALINILAM,DELTA PAWAN',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL.GAJAH MADA',
   'no': '174B',
   'kelurahan': 'DS KALINILAM',
   'kecamatan': 'DELTA PAWAN',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'DISTRIK 8, SENOPATI TOWER PROSPERITY LANTAI 9, JALAN SENOPATI DALAM I, KELURAHAN SENAYAN, KECAMATAN KEBAYORAN BARU, JAKARTA SELATAN',
  'label': {'gedung': 'SENOPATI TOWER PROSPERITY',
   'lantai': '9',
   'jalan': 'JALAN SENOPATI DALAM I',
   'no': '',
   'kelurahan': 'SENAYAN',
   'kecamatan': 'KEBAYORAN BARU',
   'kota': 'JAKARTA SELATAN',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'DISTRIK 8'}},
 {'text': 'Gedung DIPO Tower - DIPO Business Center Lantai 12 Unit G, Jalan Jend. Gatot Soebroto Kav. 51-52',
  'label': {'gedung': 'DIPO Tower - DIPO Business Center',
   'lantai': '12',
   'jalan': 'Jalan Jend. Gatot Soebroto',
   'no': 'Kav. 51-52',
   'remaining_text': ''}},
 {'text': 'Komplek Piazza Residence, Jl. Pasadena No. E-18',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jl. Pasadena',
   'no': 'E-18',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Komplek Piazza Residence'}},
 {'text': 'Gedung Wisma Raharja Lt 8, Jalan TB Simatupang Kav 1, Cilandak Timur, Jakarta Selatan Provinsi DKI Jakarta',
  'label': {'gedung': 'Wisma Raharja',
   'lantai': '8',
   'jalan': 'TB Simatupang',
   'no': '',
   'kelurahan': '',
   'kecamatan': 'Cilandak Timur',
   'kota': '',
   'provinsi': 'DKI Jakarta',
   'kodepos': '',
   'remaining_text': 'Kav 1'}},
 {'text': 'Pergudangan Laksana Business Park Gudang Blok W Nomor 22, Jalan Raya Kali Baru',
  'label': {'gedung': 'Pergudangan Laksana Business Park',
   'lantai': '',
   'jalan': 'Jalan Raya Kali Baru',
   'no': '22',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Gudang Blok W'}},
 {'text': 'HARAPAN INDAH BLOK SS 20 NOMOR 10-11',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'HARAPAN INDAH',
   'no': '10-11',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'BLOK SS 20'}},
 {'text': 'JL. RAYA AIR KENANGA RUKO KENANGA II NO.11',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL. RAYA AIR KENANGA',
   'no': 'RUKO KENANGA II NO.11',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Perumahan Taman Nuansa Tjampuhan, Jalan Professor Doktor Ida Bagus Mantra',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Professor Doktor Ida Bagus Mantra',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Perumahan Taman Nuansa Tjampuhan'}},
 {'text': 'GEDUNG OFFICE 8 LEVEL 18-A, JL. SENOPATI NO. 8 B, KAWASAN SCBD',
  'label': {'gedung': 'OFFICE 8',
   'lantai': '18-A',
   'jalan': 'JL. SENOPATI',
   'no': '8 B',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'KAWASAN SCBD'}},
 {'text': 'JALAN RAYA ANYAR GANG III No. 2',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JALAN RAYA ANYAR',
   'no': 'GANG III No. 2',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Gedung 18 Office Park Lantai 22 Suite E, F & G Jl. TB. Simatupang No. 18',
  'label': {'gedung': 'Gedung 18',
   'lantai': '22',
   'jalan': 'Jl. TB. Simatupang',
   'no': '18',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Office Park Lantai 22 Suite E & F & G'}},
 {'text': 'Gedung Kirana Three Lt 9A Kirana Commercial Avenue Jl. Boulevard Raya No 1',
  'label': {'gedung': 'Kirana Three',
   'lantai': '9A',
   'jalan': 'Kirana Commercial Avenue',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Jl. Boulevard Raya No 1'}},
 {'text': 'VILLA TANGERANG REGENCY I BE.I/17 RT.006/012 KEL. GEBANG RAYA',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': '',
   'no': 'BE.I/17',
   'kelurahan': 'GEBANG RAYA',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'RT.006/012'}},
 {'text': 'JL. RAYA KAMPUNG MELAYU, RUKO THE AIRPORT CITY BLOK A 2 - E',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL. RAYA KAMPUNG MELAYU',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'RUKO THE AIRPORT CITY BLOK A 2 - E'}},
 {'text': 'Komplek Pergudangan Pesona Kahuripan 5 Kampung Pangkalan',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': '',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Komplek Pergudangan Pesona Kahuripan 5 Kampung Pangkalan'}},
 {'text': 'GMI BUILDING, JL SRENGSENG SAWAH NO 4',
  'label': {'gedung': 'GMI BUILDING',
   'lantai': '',
   'jalan': 'JL SRENGSENG SAWAH',
   'no': '4',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Desa Keurea, kecamatan bahodopi.kabupaten morowali, propinsi Sulawesi Tengah',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': '',
   'no': '',
   'kelurahan': '',
   'kecamatan': 'bahodopi',
   'kota': '',
   'provinsi': 'Sulawesi Tengah',
   'kodepos': '',
   'remaining_text': 'Desa Keurea, kabupaten morowali'}},
 {'text': 'Gedung Jaya Lantai 5 Unit A-6, Jalan MH Thamrin Nomor 12',
  'label': {'gedung': 'Gedung Jaya',
   'lantai': '5',
   'jalan': 'Jalan MH Thamrin',
   'no': '12',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Unit A-6'}},
 {'text': 'JL.KARANG ANYAR RAYA KOMPLEK 55 BLOK B NO.24 RT.002,RW.013, SAWAH BESAR',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL.KARANG ANYAR RAYA',
   'no': '24',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'KOMPLEK 55 BLOK B RT.002,RW.013, SAWAH BESAR'}},
 {'text': 'MY REPUBLIC PLAZA, WING A ZONA 6 GREEN OFFICE PARK, JALAN BSD GRAND BOULEVARD, BSD CITY',
  'label': {'gedung': 'MY REPUBLIC PLAZA, WING A',
   'lantai': '',
   'jalan': 'JALAN BSD GRAND BOULEVARD',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'ZONA 6 GREEN OFFICE PARK, BSD CITY'}},
 {'text': 'Jalan Boulevard Graha Raya Blok A8 no 11C, 11D',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Boulevard Graha Raya',
   'no': '11C, 11D',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Kutawaringin Industrial Park (KIP), Jl. Sukawangi Kaler (Nanjung)',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jl. Sukawangi Kaler (Nanjung)',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Kutawaringin Industrial Park (KIP)'}},
 {'text': 'EIGHTYEIGHT CASABLANCA OFFICE TOWER LT.38 UNIT A-D, JL. CASABLANGKA KAV. 8',
  'label': {'gedung': 'EIGHTYEIGHT CASABLANCA OFFICE TOWER',
   'lantai': 'LT.38',
   'jalan': 'JL. CASABLANGKA',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'KAV. 8'}},
 {'text': 'JALAN INSINYUR PANGERAN MUHAMMAD NOOR NO. 72',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JALAN INSINYUR PANGERAN MUHAMMAD NOOR',
   'no': '72',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Cityloft Sudirman Lantai 19 Unit 1926',
  'label': {'gedung': 'Cityloft Sudirman',
   'lantai': '19',
   'jalan': '',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Unit 1926'}},
 {'text': 'Grand Deltasari Jalan Anthurium I nomor 16',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Anthurium I',
   'no': '16',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Grand Deltasari'}},
 {'text': 'jalan dr. sam ratulangi nomor 8',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'dr. sam ratulangi',
   'no': '8',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'SIGNATURE PARK GRANDE, JALAN LETJAN M.T. HARYONO NOMOR 20',
  'label': {'gedung': 'SIGNATURE PARK GRANDE',
   'jalan': 'JALAN LETJAN M.T. HARYONO',
   'no': '20',
   'remaining_text': ''}},
 {'text': 'Gedung The CEO, Lantai 12, Jl. TB. Simatupang No. 18C',
  'label': {'gedung': 'The CEO',
   'lantai': '12',
   'jalan': 'TB. Simatupang',
   'no': '18C',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'Kompleks Bumi Sunu Permai B 15, Jalan Al Markaz Al Islami',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Al Markaz Al Islami',
   'no': '15',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'Kompleks Bumi Sunu Permai B'}},
 {'text': 'JL. NUSA INDAH, RT 002/003, MARIYAI, MARIAT',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL. NUSA INDAH',
   'no': '',
   'kelurahan': 'MARIYAI',
   'kecamatan': 'MARIAT',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'GEDUNG GRAHA MAMPANG LANTAI 1 SUITE 101, JALAN MAMPANG PRAPATAN RAYA KAV. 100',
  'label': {'gedung': 'GRAHA MAMPANG',
   'lantai': '1',
   'jalan': 'JALAN MAMPANG PRAPATAN RAYA',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'KAV. 100, SUITE 101'}},
 {'text': 'Jalan Raya Kerobokan, Pertokoan Semerjaya Nomor : 10, Kerobokan',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'Jalan Raya Kerobokan',
   'no': '10',
   'kelurahan': 'Pertokoan Semerjaya',
   'kecamatan': 'Kerobokan',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'PERUMAHAN GRIYA KEMELAK PERSADA JALAN AIR SEMAMBU',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JALAN AIR SEMAMBU',
   'no': '',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': 'PERUMAHAN GRIYA KEMELAK PERSADA'}},
 {'text': 'JL. ABDURRACHMAN SALEH PEMBANGUNAN NOMOR 5',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL. ABDURRACHMAN SALEH PEMBANGUNAN',
   'no': '5',
   'kelurahan': '',
   'kecamatan': '',
   'kota': '',
   'provinsi': '',
   'kodepos': '',
   'remaining_text': ''}},
 {'text': 'PERUM GRIYA SUKABUMI, JL. CIAUL PASIR BLOK D1/D2, KEL. CISARUA',
  'label': {'gedung': '',
   'lantai': '',
   'jalan': 'JL. CIAUL PASIR',
   'no': '',

In [24]:
import pandas as pd

df_train = pd.DataFrame(dataset)

df_train.to_parquet(
    "train_address_1k.parquet",
    engine="pyarrow",
    index=False
)

In [25]:
df_train.to_json(
    "train_address_1k.json",
    orient="records",
    force_ascii=False,
    indent=2
)

In [26]:
print(df_train.shape)
print(df_train.head(3))

(997, 2)
                                                text  \
0  JALAN RAYA CILINCING NO 36, RUKO CILINCING PLA...
1  JALAN CENDRAWASIH PERUMAHAN TAHAP 3 NOMOR 4, K...
2  SEDAYU SQUARE Blok B 12, JALAN OUTER RINGROAD ...

                                               label
0  {'gedung': '', 'lantai': '', 'jalan': 'JALAN R...
1  {'gedung': '', 'lantai': '', 'jalan': 'JALAN C...
2  {'gedung': 'SEDAYU SQUARE', 'lantai': '', 'jal...

In [27]:
df_train

,text,label
0,"JALAN RAYA CILINCING NO 36, RUKO CILINCING PLA...","{'gedung': '', 'lantai': '', 'jalan': 'JALAN R..."
1,"JALAN CENDRAWASIH PERUMAHAN TAHAP 3 NOMOR 4, K...","{'gedung': '', 'lantai': '', 'jalan': 'JALAN C..."
2,"SEDAYU SQUARE Blok B 12, JALAN OUTER RINGROAD ...","{'gedung': 'SEDAYU SQUARE', 'lantai': '', 'jal..."
3,"GRAHA MULIA, CLUSTER DIAMOND, BLOK P7","{'gedung': 'GRAHA MULIA', 'lantai': '', 'jalan..."
4,Ruko Thematik Paramount Marketplace Blok P/51 ...,{'gedung': 'Ruko Thematik Paramount Marketplac...
...,...,...
992,"4W OFFICE, JALAN RING ROAD BUBULAK NOMOR A-4","{'gedung': '4W Office', 'lantai': '', 'jalan':..."
993,Northwest Boulevard NV 07/6 (Lantai 2),"{'gedung': '', 'lantai': '2', 'jalan': 'Northw..."
994,SPAZIO TOWER LANTAI 11 UNIT 1107 Jl. Mayjend Y...,"{'gedung': 'SPAZIO TOWER', 'lantai': '11', 'ja..."
995,"WIJAYA GRAND CENTER, JL. WIJAYA II NO.15","{'gedung': 'WIJAYA GRAND CENTER', 'lantai': ''..."
996,Gedung Grand Slipi Tower Lantai 5 unit F. Jala...,"{'gedung': 'Gedung Grand Slipi Tower', 'lantai..."

##DUMP

In [12]:
addr = df_sample["Alamat Lengkap"].iloc[0]

print(addr)

result = parse_address(addr)

print(result)
print(type(result))

JALAN RAYA CILINCING NO 36, RUKO CILINCING PLAZZA BLOK A/2
None
<class 'NoneType'>